INSERT INTO "public"."education_levels" ("name", "amount", "updated_at")
VALUES
('INICIAL', 0, CURRENT_TIMESTAMP),
('PRIMARIA', 0, CURRENT_TIMESTAMP),
('SECUNDARIA', 0, CURRENT_TIMESTAMP),
('PRE UNIVERSIDAD', 0, CURRENT_TIMESTAMP),
('SUPERIOR', 50, CURRENT_TIMESTAMP)
;
